# Generated by Django 2.2.1 on 2019-05-16 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SecuredVote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='pub_key',
        ),
        migrations.AddField(
            model_name='voter',
            name='private_key',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='public_key',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='vote',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SecuredVote.Candidate'),
        ),
    ]
