# Generated by Django 2.2.1 on 2019-05-16 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SecuredVote', '0002_auto_20190516_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='is_accepted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='candidate',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='SecuredVote.Candidate'),
            preserve_default=False,
        ),
    ]
