# Generated by Django 2.2.1 on 2019-05-16 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SecuredVote', '0004_voter_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='birth_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
