# Generated by Django 2.2.1 on 2019-05-16 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SecuredVote', '0005_candidate_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='is_accepted',
            new_name='is_valid',
        ),
    ]
