# Generated by Django 2.2.1 on 2019-05-17 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SecuredVote', '0010_auto_20190517_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=10000)),
                ('message', models.CharField(max_length=10000)),
                ('public_key', models.CharField(max_length=10000)),
            ],
        ),
        migrations.AlterField(
            model_name='revision',
            name='pending',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SecuredVote.Pending'),
        ),
        migrations.AddField(
            model_name='pending',
            name='signature',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='SecuredVote.Signature'),
            preserve_default=False,
        ),
    ]
