# Generated by Django 2.2.1 on 2019-05-17 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SecuredVote', '0013_auto_20190517_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='signature',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='SecuredVote.Signature'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='pending',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SecuredVote.Pending'),
        ),
    ]
