# Generated by Django 2.2.1 on 2019-05-17 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SecuredVote', '0015_auto_20190517_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='pending',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SecuredVote.Pending'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='public_key',
            field=models.FileField(max_length=10000, upload_to=''),
        ),
    ]
