# Generated by Django 2.2.1 on 2019-05-17 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SecuredVote', '0019_auto_20190517_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signature',
            old_name='signature',
            new_name='sig',
        ),
        migrations.AlterField(
            model_name='revision',
            name='pending',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SecuredVote.Pending'),
        ),
    ]
