# Generated by Django 2.2.1 on 2019-05-17 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SecuredVote', '0020_auto_20190517_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='pending',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SecuredVote.Pending'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='message',
            field=models.BinaryField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='signature',
            name='sig',
            field=models.BinaryField(max_length=10000),
        ),
    ]
