# Generated by Django 2.2.1 on 2019-05-17 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SecuredVote', '0023_auto_20190517_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='signature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SecuredVote.Signature'),
        ),
        migrations.AlterField(
            model_name='revision',
            name='pending',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SecuredVote.Pending'),
        ),
    ]
