# Generated by Django 2.2.1 on 2019-05-18 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SecuredVote', '0026_auto_20190518_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='voter',
        ),
        migrations.AlterField(
            model_name='revision',
            name='pending',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SecuredVote.Pending'),
        ),
    ]
