# Generated by Django 2.2.1 on 2019-05-18 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SecuredVote', '0027_auto_20190518_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pending',
            old_name='do_file',
            new_name='de_file',
        ),
        migrations.RenameField(
            model_name='revision',
            old_name='do_file',
            new_name='de_file',
        ),
        migrations.AlterField(
            model_name='revision',
            name='pending',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SecuredVote.Pending'),
        ),
    ]
